import { NextResponse } from "next/server";
import type { EmailOtpType } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/server";

/**
 * Redeems emailed invitation and password-recovery links.
 *
 * Links generated by the service-role admin client — every employee invitation
 * (`/api/admin/employees`) and every administrator-triggered reset — are not
 * PKCE, so Supabase returns their tokens in the URL *hash fragment*. A fragment
 * never reaches the server, which is why `/auth/callback` cannot redeem them:
 * it reads `code` from the query string. Templates therefore point here with
 * `token_hash`, which `verifyOtp` exchanges for a cookie session server-side.
 *
 * `/auth/callback` stays in place for genuine PKCE browser flows.
 *
 * A link that carries its tokens in the fragment instead is no longer a dead
 * end: this route hands it to `/login`, which completes it in the browser.
 * That is what lets the default templates work, so email onboarding no longer
 * depends on two hand-edited dashboard fields staying correct.
 */
const allowedTypes = new Set<EmailOtpType>([
  "invite",
  "recovery",
  "signup",
  "magiclink",
  "email",
  "email_change",
]);

function safePath(value: string | null) {
  return value?.startsWith("/") && !value.startsWith("//") ? value : "/";
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type") as EmailOtpType | null;
  const code = url.searchParams.get("code");
  const next = safePath(url.searchParams.get("next"));
  const client = await createClient();
  if (tokenHash && type && allowedTypes.has(type)) {
    const result = await client.auth.verifyOtp({ token_hash: tokenHash, type });
    if (!result.error) return NextResponse.redirect(new URL(next, url.origin));
  } else if (code) {
    // A browser-initiated PKCE reset still arrives with a code. Accepting both
    // here keeps every emailed link working through one route.
    const result = await client.auth.exchangeCodeForSession(code);
    if (!result.error) return NextResponse.redirect(new URL(next, url.origin));
  }
  // Nothing redeemable in the query string. That is the expected shape when the
  // template uses the default `{{ .ConfirmationURL }}`: Supabase returns those
  // tokens in the URL *fragment*, which never reaches a server. The fragment
  // survives this redirect, so the sign-in page picks it up client-side and
  // finishes the exchange there rather than stranding the employee. `next` is
  // carried across so it still knows where to send them afterwards.
  const failure = new URL("/login", url.origin);
  failure.searchParams.set("error", "auth_confirm");
  failure.searchParams.set("next", next);
  return NextResponse.redirect(failure);
}
