import { NextResponse } from "next/server";
import type { EmailOtpType } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/server";

/**
 * Redeems emailed invitation and password-recovery links.
 *
 * Links generated by the service-role admin client — every employee invitation
 * (`/api/admin/employees`) and every administrator-triggered reset — are not
 * PKCE, so Supabase returns their tokens in the URL *hash fragment*. A fragment
 * never reaches the server, which is why `/auth/callback` cannot redeem them:
 * it reads `code` from the query string. Templates therefore point here with
 * `token_hash`, which `verifyOtp` exchanges for a cookie session server-side.
 *
 * `/auth/callback` stays in place for genuine PKCE browser flows.
 */
const allowedTypes = new Set<EmailOtpType>([
  "invite",
  "recovery",
  "signup",
  "magiclink",
  "email",
  "email_change",
]);

function safePath(value: string | null) {
  return value?.startsWith("/") && !value.startsWith("//") ? value : "/";
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  const tokenHash = url.searchParams.get("token_hash");
  const type = url.searchParams.get("type") as EmailOtpType | null;
  const code = url.searchParams.get("code");
  const next = safePath(url.searchParams.get("next"));
  const client = await createClient();
  if (tokenHash && type && allowedTypes.has(type)) {
    const result = await client.auth.verifyOtp({ token_hash: tokenHash, type });
    if (!result.error) return NextResponse.redirect(new URL(next, url.origin));
  } else if (code) {
    // A browser-initiated PKCE reset still arrives with a code. Accepting both
    // here keeps every emailed link working through one route.
    const result = await client.auth.exchangeCodeForSession(code);
    if (!result.error) return NextResponse.redirect(new URL(next, url.origin));
  }
  return NextResponse.redirect(new URL("/login?error=auth_confirm", url.origin));
}
